import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gradient-to-t from-green-400 via-cyan-900 to-blue-500 h-full overflow-x-hidden ${inter.className}`}>{children}</body>
    </html>
  )
}
